apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.appName }}-service"
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:    
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080