pipeline {
    agent any

    stages {
        stage("Init") {
            step {
                sh 'echo Init'
            }
        }

        stage("Prep workspace") {
            step {
                sh 'echo Prep workspace'
            }
        }
    }
}